name: Tauri Build

on:
  push:
    branches: [ main ]

jobs:
  tauri-build:
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Tauri dependencies
        run: npm install

      - name: Tauri Build
        run: npm run tauri build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ matrix.platform }}
          path: src-tauri/target/release/
